### DISCUSSION TITLE
Clickhouse Connection Refused

### DISCUSSION THREAD

**Discussion by CactusChaos** [th0th/poeticmetric#195] [Self-hosted help]
Hi, 
I am unable to access the web portal after install. On checking the logs I am getting:

```
poeticmetric-worker-1  | goroutine 1 [running]:
poeticmetric-worker-1  | log.Panicln({0x40003dfea0?, 0x2a?, 0x400050e240?})
poeticmetric-worker-1  |        /usr/local/go/src/log/log.go:446 +0x60
poeticmetric-worker-1  | main.main()
poeticmetric-worker-1  |        /usr/src/poeticmetric/cmd/migrator/main.go:69 +0x360
poeticmetric-worker-1  | 2023/08/27 01:30:44 dial tcp 172.24.0.3:9000: connect: connection refused
poeticmetric-worker-1  | panic: dial tcp 172.24.0.3:9000: connect: connection refused
```
I have a couple of the external ports remapped due to already existing services running on them.

My .env file:
```
# CLICKHOUSE
CLICKHOUSE_DATABASE=poeticmetric
CLICKHOUSE_HOST=clickhouse
CLICKHOUSE_PASSWORD=##
CLICKHOUSE_TCP_PORT=9000
CLICKHOUSE_USER=poeticmetric

# DOCKER COMPOSE
COMPOSE_PROJECT_NAME=poeticmetric

# GOOGLE
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# POETICMETRIc
FRONTEND_BASE_URL=http://localhost:8000
REST_API_BASE_URL=http://localhost:8001
VERSION=latest
WORKER_COUNT=2

# POSTGRES
POSTGRES_DATABASE=poeticmetric
POSTGRES_HOST=postgres
POSTGRES_PASSWORD=##
POSTGRES_PORT=5432
POSTGRES_USER=poeticmetric

# RABBITMQ
RABBITMQ_HOST=rabbitmq
RABBITMQ_PASSWORD=##
RABBITMQ_PORT=5672
RABBITMQ_USER=poeticmetric
RABBITMQ_VHOST=poeticmetric

# REDIS
REDIS_HOST=redis
REDIS_PASSWORD=##
REDIS_PORT=6379

# SMTP
SMTP_FROM=poeticmetric
SMTP_HOST=smtp.zoho.com.au
SMTP_PASSWORD=##
SMTP_PORT=465
SMTP_USER=##
```
Docker compose:
```
version: "3.9"

x-backend-common: &backend-common
  depends_on:
    - clickhouse
    - postgres
    - rabbitmq
    - redis
  image: "poeticmetric/backend:${VERSION}"
  environment: &backend-common-environment
    CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE}
    CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
    CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    CLICKHOUSE_TCP_PORT: ${CLICKHOUSE_TCP_PORT}
    CLICKHOUSE_USER: ${CLICKHOUSE_USER}
    FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
    POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    POSTGRES_HOST: ${POSTGRES_HOST}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_PORT: ${POSTGRES_PORT}
    POSTGRES_USER: ${POSTGRES_USER}
    RABBITMQ_HOST: ${RABBITMQ_HOST}
    RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    RABBITMQ_PORT: ${RABBITMQ_PORT}
    RABBITMQ_USER: ${RABBITMQ_USER}
    RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PASSWORD: ${REDIS_PASSWORD}
    REDIS_PORT: ${REDIS_PORT}
    REST_API_BASE_URL: ${REST_API_BASE_URL}
    SMTP_FROM: ${SMTP_FROM}
    SMTP_HOST: ${SMTP_HOST}
    SMTP_PASSWORD: ${SMTP_PASSWORD}
    SMTP_PORT: ${SMTP_PORT}
    SMTP_USER: ${SMTP_USER}
    WORKER_COUNT: ${WORKER_COUNT}
  restart: unless-stopped
  tty: true

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}

volumes:
  postgres:
  clickhouse:

services:
  clickhouse:
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DATABASE}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
    image: clickhouse/clickhouse-server:latest-alpine
    volumes:
      - clickhouse:/var/lib/clickhouse
    ports:
      - "9002:9000"

  frontend:
    environment:
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      REST_API_BASE_URL: ${REST_API_BASE_URL}
    image: "poeticmetric/frontend:${VERSION}"
    ports:
      - "8002:8000"

  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    image: rabbitmq:3-management-alpine

  redis:
    command:
      - "redis-server"
      - "--requirepass"
      - "${REDIS_PASSWORD}"
    image: redis:7-alpine

  rest-api:
    <<: *backend-common
    environment:
      <<: *backend-common-environment
      INSTANCE: rest-api
    ports:
      - "8003:8001"

  scheduler:
    <<: *backend-common
    depends_on:
      - rabbitmq
    environment:
      <<: *backend-common-environment
      INSTANCE: scheduler

  worker:
    <<: *backend-common
    environment:
      <<: *backend-common-environment
      INSTANCE: worker
```
NGINX:
```
server {
        server_name poeticmetric.##;
        location / {
        proxy_pass http://localhost:8002/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /api/ {
        proxy_pass http://localhost:8003/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/poeticmetric.##/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/poeticmetric.##/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = poeticmetric.##) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name poeticmetric.##;
    listen 80;
    return 404; # managed by Certbot
}
```

Note ## is just redacted information :)
