### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by JustinBack** [th0th/poeticmetric#191]
Tried to install Poeticmetric today and I am facing an issue with the google integration (it should be disabled)

<details><summary>docker-compose.yml</summary>
<p>

```yml
version: '3.9'

x-backend-common: &backend-common
  links:
    - clickhouse
    - postgres
    - rabbitmq
    - redis
  image: "poeticmetric/backend:${VERSION}"
  environment: &backend-common-environment
    CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE}
    CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
    CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    CLICKHOUSE_TCP_PORT: ${CLICKHOUSE_TCP_PORT}
    CLICKHOUSE_USER: ${CLICKHOUSE_USER}
    FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
    POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    POSTGRES_HOST: ${POSTGRES_HOST}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_PORT: ${POSTGRES_PORT}
    POSTGRES_USER: ${POSTGRES_USER}
    RABBITMQ_HOST: ${RABBITMQ_HOST}
    RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    RABBITMQ_PORT: ${RABBITMQ_PORT}
    RABBITMQ_USER: ${RABBITMQ_USER}
    RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PASSWORD: ${REDIS_PASSWORD}
    REDIS_PORT: ${REDIS_PORT}
    REST_API_BASE_URL: ${REST_API_BASE_URL}
    SMTP_FROM: ${SMTP_FROM}
    SMTP_HOST: ${SMTP_HOST}
    SMTP_PASSWORD: ${SMTP_PASSWORD}
    SMTP_PORT: ${SMTP_PORT}
    SMTP_USER: ${SMTP_USER}
    WORKER_COUNT: ${WORKER_COUNT}
  restart: unless-stopped
  tty: true

  
volumes:
  clickhouse:
  postgres:

services:
  
  clickhouse:
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DATABASE}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
    image: clickhouse/clickhouse-server:latest-alpine
    volumes:
      - clickhouse:/var/lib/clickhouse
    
  frontend:
    environment:
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      REST_API_BASE_URL: ${REST_API_BASE_URL}
    image: "poeticmetric/frontend:${VERSION}"
    networks:
      - net
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      - "traefik.http.services.${TRAEFIK_ROUTER_NAME}.loadbalancer.server.port=${TRAEFIK_SERVICE_PORT}"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-http.rule=${TRAEFIK_ROUTER_RULE}"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-http.service=${TRAEFIK_ROUTER_NAME}"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-http.middlewares=redirect-to-https,global"

      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https.rule=${TRAEFIK_ROUTER_RULE}"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https.middlewares=compress,global"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https.service=${TRAEFIK_ROUTER_NAME}"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https.tls=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https.tls.certresolver=letsencrypt"

  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    image: rabbitmq:3-management-alpine

  redis:
    command:
      - "redis-server"
      - "--requirepass"
      - "${REDIS_PASSWORD}"
    image: redis:7-alpine

  rest-api:
    <<: *backend-common
    environment:
      <<: *backend-common-environment
      INSTANCE: rest-api
    networks:
      - net
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      - "traefik.http.services.${TRAEFIK_ROUTER_NAME}_api.loadbalancer.server.port=${TRAEFIK_SERVICE_PORT}"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-http_api.rule=${TRAEFIK_ROUTER_RULE_API}"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-http_api.entrypoints=web"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-http_api.service=${TRAEFIK_ROUTER_NAME}_api"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-http_api.middlewares=redirect-to-https,global"

      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https_api.rule=${TRAEFIK_ROUTER_RULE_API}"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https_api.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https_api.middlewares=compress,global"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https_api.service=${TRAEFIK_ROUTER_NAME}_api"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https_api.tls=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}-https_api.tls.certresolver=letsencrypt"


  scheduler:
    <<: *backend-common
    environment:
      <<: *backend-common-environment
      INSTANCE: scheduler

  worker:
    <<: *backend-common
    environment:
      <<: *backend-common-environment
      INSTANCE: worker

networks:
  net:
    external:
      name: traefik-net
```

</p>
</details> 

I even tried setting the client_id and secret to blank string, but I am faced with this error:

```js
Object { message: "Missing required parameter client_id.", stack: "To@https://accounts.google.com/gsi/client:223:388\nUo@https://accounts.google.com/gsi/client:218:328\nbq@https://accounts.google.com/gsi/client:269:395\ngq@https://accounts.google.com/gsi/client:272:336\n@https://accounts.google.com/gsi/client:277:634\n57026/s/<@https://**HIDDEN**/_next/static/chunks/pages/_app-52e3daee83b90dfb.js:14:259820\nuI@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:84130\noU@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:113203\no@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:107748\nx@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:33:1374\nT@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:33:1903\nEventHandlerNonNull*85568@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:33:2072\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n22962@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:33:3834\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n53746@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:34\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n10422@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:129120\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n44478@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:128820\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n97296@https://**HIDDEN**/_next/static/chunks/main-b1e5ec28880e82ef.js:1:5833\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n60942@https://**HIDDEN**/_next/static/chunks/main-b1e5ec28880e82ef.js:1:14165\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n@https://**HIDDEN**/_next/static/chunks/main-b1e5ec28880e82ef.js:1:101985\nf.O@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:589\n@https://**HIDDEN**/_next/static/chunks/main-b1e5ec28880e82ef.js:1:102007\ni@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:3448\n@https://**HIDDEN**/_next/static/chunks/main-b1e5ec28880e82ef.js:1:51\n", type: "missing_required_parameter" }
​
message: "Missing required parameter client_id."
​
stack: "To@https://accounts.google.com/gsi/client:223:388\nUo@https://accounts.google.com/gsi/client:218:328\nbq@https://accounts.google.com/gsi/client:269:395\ngq@https://accounts.google.com/gsi/client:272:336\n@https://accounts.google.com/gsi/client:277:634\n57026/s/<@https://**HIDDEN**/_next/static/chunks/pages/_app-52e3daee83b90dfb.js:14:259820\nuI@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:84130\noU@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:113203\no@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:107748\nx@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:33:1374\nT@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:33:1903\nEventHandlerNonNull*85568@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:33:2072\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n22962@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:33:3834\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n53746@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:34\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n10422@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:129120\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n44478@https://**HIDDEN**/_next/static/chunks/framework-281bd828f4ecdac7.js:9:128820\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n97296@https://**HIDDEN**/_next/static/chunks/main-b1e5ec28880e82ef.js:1:5833\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n60942@https://**HIDDEN**/_next/static/chunks/main-b1e5ec28880e82ef.js:1:14165\nf@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:163\n@https://**HIDDEN**/_next/static/chunks/main-b1e5ec28880e82ef.js:1:101985\nf.O@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:589\n@https://**HIDDEN**/_next/static/chunks/main-b1e5ec28880e82ef.js:1:102007\ni@https://**HIDDEN**/_next/static/chunks/webpack-41ba7a9d299e8234.js:1:3448\n@https://**HIDDEN**/_next/static/chunks/main-b1e5ec28880e82ef.js:1:51\n"
​
type: "missing_required_parameter"
​
```

Is there any fix? I used the self-hosted docker-compose as a base
